import { getAdminDb } from "@/lib/firebase/admin";
import { getWhatsAppConnection, getWhatsAppTemplateConfig, sendWhatsAppTemplate } from "@/lib/whatsapp/server";

type S = { id:string; name:string; durationMinutes:number; price:number };
type P = { id:string; name:string; serviceIds:string[]; schedule?:Record<string, any>; timeOffDates?:string[] };
type State = { serviceId:string; specialistId:string; specialistName:string; date:string; time:string; customerName:string; expiresAt:number };
const DAYS=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"];
const norm=(v:string)=>v.toLocaleLowerCase("tr-TR").replace(/[İı]/g,"i").replace(/[Şş]/g,"s").replace(/[Ğğ]/g,"g").replace(/[Üü]/g,"u").replace(/[Öö]/g,"o").replace(/[Çç]/g,"c").trim();
const min=(v:string)=>{const p=v.split(":").map(Number);return p[0]*60+p[1]};
const tm=(v:number)=>String(Math.floor(v/60)).padStart(2,"0")+":"+String(v%60).padStart(2,"0");
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const add=(d:string,n:number)=>{const p=d.split("-").map(Number),x=new Date(Date.UTC(p[0],p[1]-1,p[2]));x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const fmt=(d:string)=>{const p=d.split("-");return p[2]+"."+p[1]+"."+p[0]};
function dateOf(t:string){const v=norm(t),d=today();if(v.includes("bugun"))return d;if(v.includes("yarin"))return add(d,1);const m=v.match(/(?:^|\s)(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?(?:\s|$)/);if(!m)return;const y=m[3]?Number(m[3].length===2?"20"+m[3]:m[3]):Number(d.slice(0,4)),x=new Date(Date.UTC(y,Number(m[2])-1,Number(m[1])));return x.getUTCMonth()===Number(m[2])-1&&x.getUTCDate()===Number(m[1])?x.toISOString().slice(0,10):undefined}
function timeOf(t:string){const m=t.match(/(?:saat\s*)?(\d{1,2})(?::(\d{2}))?\s*(?:da|de|ta|te)?/i);if(!m)return;const h=Number(m[1]),n=Number(m[2]||0);return h<24&&n<60?tm(h*60+n):undefined}
async function data(bid:string){const r=getAdminDb().collection("businesses").doc(bid),x=await Promise.all([r.get(),r.collection("services").get(),r.collection("specialists").get(),r.collection("hours").get()]);const services:S[]=x[1].docs.map(d=>({id:d.id,name:String(d.data().name||""),durationMinutes:Number(d.data().durationMinutes||30),price:Number(d.data().price||0)})).filter(s=>s.name);const specialists:P[]=x[2].docs.map(d=>{const a=d.data();return{id:d.id,name:String(a.name||""),serviceIds:Array.isArray(a.serviceIds)?a.serviceIds.filter((z):z is string=>typeof z==="string"):[],schedule:a.schedule,timeOffDates:Array.isArray(a.timeOffDates)?a.timeOffDates.filter((z):z is string=>typeof z==="string"):[]}});const hours:Record<string,any>={};x[3].docs.forEach(d=>hours[d.id]=d.data());return{business:x[0].data()||{},services,specialists,hours}}
async function slots(bid:string,s:S,ps:P,hours:Record<string,any>,date:string,wanted?:string){const out:any[]=[],dur=Math.max(30,Math.ceil(s.durationMinutes/30)*30),day=DAYS[new Date(date+"T12:00:00Z").getUTCDay()],db=getAdminDb();for(const p of ps.filter(z=>z.serviceIds.includes(s.id))){if(p.timeOffDates?.includes(date))continue;const h=p.schedule?.[day]||hours[day];if(!h?.enabled||!h.open||!h.close)continue;const snap=await db.collection("businesses").doc(bid).collection("slots").where("date","==",date).where("specialistId","==",p.id).get(),taken=new Set(snap.docs.map(d=>String(d.data().time||"")));for(let v=min(h.open);v+dur<=min(h.close);v+=30){const parts=Array.from({length:dur/30},(_,i)=>tm(v+i*30));if(parts.some(z=>taken.has(z)))continue;if(h.breakStart&&h.breakEnd&&parts.some(z=>min(z)>=min(h.breakStart)&&min(z)<min(h.breakEnd)))continue;const t=tm(v);if(wanted&&t!==wanted)continue;out.push({date,time:t,specialistId:p.id,specialistName:p.name});if(wanted||out.length>=3)return out}}return out}
async function getState(bid:string,phone:string){const x=await getAdminDb().collection("businesses").doc(bid).collection("whatsappConversations").doc(phone).get();if(!x.exists)return;const s=x.data() as State;return s.expiresAt>Date.now()?s:undefined}
async function setState(bid:string,phone:string,s:State){await getAdminDb().collection("businesses").doc(bid).collection("whatsappConversations").doc(phone).set(s)}
function ref(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",v=new Uint32Array(5);crypto.getRandomValues(v);return Array.from(v,x=>a[x%a.length]).join("")}
async function create(bid:string,s:S,slot:any,name:string,phone:string){const db=getAdminDb(),base=db.collection("businesses").doc(bid),dur=Math.max(30,Math.ceil(s.durationMinutes/30)*30),ts=Array.from({length:dur/30},(_,i)=>tm(min(slot.time)+i*30)),id=ref(),b=base.collection("bookings").doc(id),rs=ts.map(t=>base.collection("slots").doc((slot.date+"_"+t+"_"+slot.specialistId).replace(/[^a-zA-Z0-9_-]/g,"-")));await db.runTransaction(async tx=>{const bs=await tx.get(b),ss=await Promise.all(rs.map(r=>tx.get(r)));if(bs.exists||ss.some(q=>q.exists))throw new Error("SLOT_TAKEN");rs.forEach((r,i)=>tx.set(r,{slotId:r.id,date:slot.date,time:ts[i],specialistId:slot.specialistId,status:"pending",createdAt:new Date()}));tx.set(b,{businessId:bid,referenceNo:id,serviceId:s.id,serviceName:s.name,serviceDurationMinutes:s.durationMinutes,servicePrice:s.price,specialistId:slot.specialistId,specialistName:slot.specialistName,customerName:name,customerPhone:phone,date:slot.date,time:slot.time,whatsappOptIn:true,status:"pending",slotId:rs[0].id,createdAt:new Date()})});return id}
export async function handleSecretaryMessage(bid:string,phone:string,text:string,customerName:string){const d=await data(bid),v=norm(text),state=await getState(bid,phone);if(state&&["evet","onay","onayla","tamam","olur"].includes(v)){const s=d.services.find(x=>x.id===state.serviceId);if(!s)return"Hizmet artık aktif değil. Yeni bir randevu isteği yazabilirsiniz.";try{const id=await create(bid,s,{date:state.date,time:state.time,specialistId:state.specialistId,specialistName:state.specialistName},state.customerName||customerName||"WhatsApp müşterisi",phone);return"Randevunuz oluşturuldu. ✅\n\n"+s.name+"\n"+state.specialistName+"\n"+fmt(state.date)+" "+state.time+"\n\nReferans: "+id}catch{return"Seçtiğiniz saat az önce alınmış. Başka bir saat deneyelim mi?"}}if(v==="iptal"||v.includes("randevu iptal")){const refNo=extractReference(text);if(!refNo)return"İptal işlemi için 5 karakterli randevu referans numaranızı yazın.";const result=await cancelBooking(bid,refNo);return result.ok?"Randevunuz iptal edildi. ✅\\n\\nReferans: "+refNo:result.message;}
  if(v.includes("randevum")||v.includes("randevu sorgu")){const refNo=extractReference(text);if(!refNo)return"Randevunuzu kontrol etmek için 5 karakterli referans numaranızı yazın.";return lookupBooking(bid,refNo);}if(["merhaba","selam","slm","hey"].includes(v))return"Merhaba 👋 "+(d.business.name||"işletmemiz")+" için randevu konusunda yardımcı olabilirim. Örn: “Yarın 15:00 manikür istiyorum.”";const s=d.services.find(x=>{const n=norm(x.name);return v.includes(n)||n.split(/\s+/).some(w=>w.length>=4&&v.includes(w))});if(!s)return d.services.length?"Tabii 😊 Hangi hizmet için randevu istiyorsunuz?\n\n"+d.services.slice(0,8).map(x=>"• "+x.name).join("\n"):"Şu anda tanımlı bir hizmet bulunmuyor.";const wanted=timeOf(text),day=dateOf(text),dates=day?[day]:Array.from({length:7},(_,i)=>add(today(),i+1));let found:any[]=[];for(const x of dates){found=await slots(bid,s,d.specialists,d.hours,x,wanted);if(found.length)break}if(!found.length)return wanted?s.name+" için "+(day?fmt(day):"istediğiniz gün")+" "+wanted+" saatinde müsaitlik bulamadım. Başka bir saat deneyelim mi?":s.name+" için yakın tarihlerde uygun saat bulamadım. Farklı bir gün deneyelim mi?";const f=found[0];await setState(bid,phone,{serviceId:s.id,specialistId:f.specialistId,specialistName:f.specialistName,date:f.date,time:f.time,customerName:customerName||"WhatsApp müşterisi",expiresAt:Date.now()+900000});const alt=found.slice(1).map(x=>fmt(x.date)+" "+x.time+" — "+x.specialistName).join("\n");return"Müsait bir saat buldum. 😊\n\n"+s.name+"\n"+f.specialistName+"\n"+fmt(f.date)+" "+f.time+"\n\nBu saati onaylıyor musunuz? “Evet” yazabilirsiniz."+ (alt?"\n\nAlternatifler:\n"+alt:"")}
export async function sendSecretaryReply(bid:string,to:string,message:string){const c=await getWhatsAppConnection(bid),t=process.env.WHATSAPP_SECRETARY_REPLY_TEMPLATE;if(!c||!t)return false;const cfg=getWhatsAppTemplateConfig();await sendWhatsAppTemplate(c.phoneNumberId,c.accessToken,to,t,cfg.language,[message]);return true}